language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean install

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
