language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -Ddocker.build.skip=false -Ddocker.reg=$DOCKER_REGISTRY -Ddocker.reg.username=$DOCKER_USERNAME -Ddocker.reg.password=$DOCKER_PASSWORD clean install

after_success:
  - mvn clean cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
