# 1. Choose language and target JDKs for parallel builds.
language: scala
scala:
  - 2.11.11
jdk:
  - oraclejdk8

# 2. Setup cache directory for Maven.
cache:
  directories:
  - $HOME/.m2

# 3. Turn off notifications.
notifications:
  email: false

