language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean install

after_success:
  - mvn clean cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
